// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/js/greeter/greeter.js', ['js.greeter'], ['goog.dom', 'js.greeter.greeting'], false);
goog.addDependency('../../../../src/js/greeter/greeting.js', ['js.greeter.greeting'], [], false);
